import * as z from 'zod/v4';
import { categoryInputSchema } from './shared.js';
import { imageCategory } from './images.js';
import { musicCategory } from './music.js';
import { newsCategory } from './news.js';
import { videoCategory } from './videos.js';
import { toCategorySearchParams, type SearchParams } from '../schemas.js';

// Media-category schemas are generated by the registry: input from the shared
// atoms, output from the definition's envelope schema (D1).
export const imageSearchInput = categoryInputSchema({
  supportsTimeRange: imageCategory.upstream.supportsTimeRange,
});
export type ImageSearchInput = z.infer<typeof imageSearchInput>;
export const imageSearchOutput = imageCategory.envelopeSchema;
export type ImageSearchResponse = z.infer<typeof imageSearchOutput>;
export type ImageSearchResult = z.infer<(typeof imageSearchOutput.shape)['results']['element']>;

export const newsSearchInput = categoryInputSchema({
  supportsTimeRange: newsCategory.upstream.supportsTimeRange,
});
export type NewsSearchInput = z.infer<typeof newsSearchInput>;
export const newsSearchOutput = newsCategory.envelopeSchema;
export type NewsSearchResponse = z.infer<typeof newsSearchOutput>;
export type NewsSearchResult = z.infer<(typeof newsSearchOutput.shape)['results']['element']>;

export const videoSearchInput = categoryInputSchema({
  supportsTimeRange: videoCategory.upstream.supportsTimeRange,
});
export type VideoSearchInput = z.infer<typeof videoSearchInput>;
export const videoSearchOutput = videoCategory.envelopeSchema;
export type VideoSearchResponse = z.infer<typeof videoSearchOutput>;
export type VideoSearchResult = z.infer<(typeof videoSearchOutput.shape)['results']['element']>;

export const musicSearchInput = categoryInputSchema({
  supportsTimeRange: musicCategory.upstream.supportsTimeRange,
});
export type MusicSearchInput = z.infer<typeof musicSearchInput>;
export const musicSearchOutput = musicCategory.envelopeSchema;
export type MusicSearchResponse = z.infer<typeof musicSearchOutput>;
export type MusicSearchResult = z.infer<(typeof musicSearchOutput.shape)['results']['element']>;

export function toImageSearchParams(input: ImageSearchInput): SearchParams {
  return toCategorySearchParams(input, imageCategory.upstream);
}

export function toNewsSearchParams(input: NewsSearchInput): SearchParams {
  return toCategorySearchParams(input, newsCategory.upstream);
}

export function toVideoSearchParams(input: VideoSearchInput): SearchParams {
  return toCategorySearchParams(input, videoCategory.upstream);
}

export function toMusicSearchParams(input: MusicSearchInput): SearchParams {
  return toCategorySearchParams(input, musicCategory.upstream);
}
